
name: ci-cd


on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4


      - name: Initialize python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-ci.txt
        
      - name: Test checking
        run: make test

      - name: Style checking
        run: make lint

      - name: Docker build checking
        run: make docker_build

      - name: Docker build mongo checking
        run: make docker_build_mongo

      - name: Docker up checking
        run: make docker_up

      - name: Docker down checking
        run: make docker_down
