
name: ci-cd


on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Initialize python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r  requirements.txt

      - name: Style checking
        run: make lint

      - name: Testing
        env:
          MODE: ${{secrets.MODE}}
          MONGODB_URI_TESTS: ${{ secrets.MONGODB_URI_TESTS }}
          MONGODB_DATABASE_TESTS: ${{ secrets.MONGODB_DATABASE_TESTS }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CLIENT_GOOGLE_ID: ${{ secrets.CLIENT_GOOGLE_ID }}
          CLIENT_SECRET_KEY: ${{ secrets.CLIENT_SECRET_KEY }}
          SECRET_KEY_ACCESS: ${{ secrets.SECRET_KEY_ACCESS }}
          SECRET_KEY_REFRESH: ${{ secrets.SECRET_KEY_REFRESH }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          ACCESS_TIME_TOKEN: ${{ secrets.ACCESS_TIME_TOKEN }}
          REFRESH_TOKEN_EXPIRATION: ${{ secrets.REFRESH_TOKEN_EXPIRATION }}

        run: |
          make docker_build_mongodb
          make tests

      - name: build_container
        run: make docker_build

      - name: container_down
        run: docker_down
