
name: ci-cd


on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  workflow_dispatch:

env:
  MONGODB_DATABASE_TESTS: ${{secrets.MONGODB_DATABASE_TESTS}}
  MONGODB_URL_TESTS: ${{secrets.MONGODB_URL_TESTS}}
  SECRET_KEY_ACCES: ${{secrets.SECRET_KEY_ACCES}}
  SECRET_KEY_REFRESH: ${{secrets.SECRET_KEY_REFRESH}}
  ALGORITHM: ${{secrets.ALGORITHM}}
  ACCESS_TIME_TOKEN: ${{secrets.ACCES_TIME_TOKEN}}
  REFRESH_TOKEN_EXPIRATION: ${{secrets.REFRESH_TOKEN}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Initialize python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create dependencies
        run:  make ve

      - name: Test Confirm
        run: make test

      - name: Style checking
        run: make lint
