
name: ci-cd


on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  workflow_dispatch:

env:
  MONGODB_DATABASE_TESTS: ${{secrets.MONGODB_DATABASE_TESTS}}
  MONGODB_URI_TESTS: ${{secrets.MONGODB_URI_TESTS}}
  MONGODB_NAME: ${{secrets.MONGODB_NAME}}
  MONGODB_URL: ${{secrets.MONGODB_URL}}


  SECRET_KEY_ACCESS: ${{secrets.SECRET_KEY_ACCESS}}
  SECRET_KEY_REFRESH: ${{secrets.SECRET_KEY_REFRESH}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  ALGORITHM: ${{secrets.ALGORITHM}}
  ACCESS_TIME_TOKEN: ${{secrets.ACCESS_TIME_TOKEN}}
  REFRESH_TOKEN_EXPIRATION: ${{secrets.REFRESH_TOKEN_EXPIRATION}}
  CLIENT_GOOGLE_ID: ${{secrets.CLIENT_GOOGLE_ID}}
  CLIENT_SECRET_KEY: ${{secrets.CLIENT_SECRET_KEY}}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Initialize python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create dependencies
        run:  make ve

      - name: Test Confirm
        run: make test

      - name: Style checking
        run: make lint
